config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :volunteer_position_contacts
  resources :user_informations, :concerns => :paginatable

  resources :user_applications, :concerns => :paginatable do
    collection do
      get 'success', action: :success
      get ':id/review', action: :review, as: :review
      get ':id/view', action: :view, as: :view
      post 'accept_or_deny', action: :accept_or_deny
      post 'reset/:id', action: :reset
    end
  end

  resources :volunteer_positions

  devise_for :users, controllers: {sessions: 'sessions'}

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Upmin::Engine => '/admin'
  end

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/permissions' => 'pages#permissions'
  get '/codeofconduct' => 'pages#code_of_conduct'
  get '/user_information/fake' => 'pages#fake_user_info'
  get '/privacypolicy' => 'pages#privacy'
  get '/help' => 'pages#help'

  # Two factor authentication routes
  get '/two_factor_authentication' => 'users#two_factor_authentication'
  get '/two_factor_authentication/configure' => 'users#setup_2fa'
  post '/two_factor_authentication/enable' => 'users#enable_2fa'
  post '/two_factor_authentication/disable' => 'users#disable_2fa'
  get '/two_factor_authentication/disable' => 'users#prepare_disable_2fa'

  # Reports routes
  get '/reports' => 'reports#index'
  get '/reports/export_user_applications'
  post '/reports/export_user_applications'
  get '/reports/position_popularity' => 'reports#position_picks'
  get '/reports/user_distribution' => 'reports#user_completion'
  get '/reports/t_shirt_distribution'
  get '/reports/user_sign_up_distribution'
  get '/reports/user_last_sign_in_at'
  get '/reports/volunteer_application_comments', concerns: :paginatable
  get '/reports/volunteer_application_comments_export'

end

app/views/pages/_banner.html.erb
<div class="banner">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <h2>Connect on social media:</h2>
        </div>
        <div class="col-lg-6">
          <ul class="list-inline banner-social-buttons">
            <li>
              <a href="https://twitter.com/ottawajazz" class="btn btn-default btn-lg">
                <i class="fa fa-twitter fa-fw"></i>
                <span class="network-name">Twitter</span>
              </a>
            </li>
            <li>
              <a href="https://facebook.com/ottawajazz" class="btn btn-default btn-lg">
                <i class="fa fa-facebook fa-fw"></i>
                <span class="network-name">Facebook</span>
              </a>
            </li>
            <li>
              <a href="https://plus.google.com/108728404704036011378/posts" class="btn btn-default btn-lg">
                <i class="fa fa-google-plus fa-fw"></i>
                <span class="network-name">Google+</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- /.container -->
  </div>
  <!-- /.banner -->

app/views/pages/_faq.html.erb
<h2>Frequently Asked Questions</h2>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      What sort of information do you collect?
    </h4>
  </div>
  <div class="panel-body">
    We've created an
    <a href="<%= user_information_fake_path %>" target="_BLANK">example page</a>
    of what a typical application looks like.
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      Are there any perks to volunteering at the Ottawa Jazz Festival?
    </h4>
  </div>
  <div class="panel-body">
    Yes! One of which is that you get a free pass to all festival events;
    <i>after</i>
    you've worked your minimum of 4 shifts.
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      I haven't received any emails from Jazzify.
    </h4>
  </div>
  <div class="panel-body">
    Please look in your
    <b>junk folder</b>.
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      The links in my email don't work.
    </h4>
  </div>
  <div class="panel-body">Try opening the link in
    <a href="https://www.google.com/chrome/browser" target="_blank">Google Chrome</a>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      Can I help in the development process?
    </h4>
  </div>
  <div class="panel-body">
    Absolutely! Please contact us at using by clicking on the
    <%= link_to 'email us', help_path + '#email_us' %>
    button.
    <br>
    Code review? Pull request? Check out Jazzify's source code on
    <a href="https://github.com/seanlf/jazzify">GitHub</a>.
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      My question isn't listed / your answers didn't work
    </h4>
  </div>
  <div class="panel-body">
    Please contact us at using by clicking on the
    <%= link_to 'email us', help_path + '#email_us' %>
    button.
  </div>
</div>

app/views/pages/_footer.html.erb
<footer class="landing-footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-inline">
            <li>
              <a href="/">Home</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="/about">About</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <%= link_to "Privacy Policy", privacypolicy_path %>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="http://ottawajazzfestival.com/contact">Contact</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="https://github.com/seanlf/jazzify"><i class='fa fa-github'>&nbsp;</i></a>
            </li>
          </ul>
          <p class="copyright text-muted small">
            Copyright &copy; Jazzify <%= Time.new.year %>. &nbsp;
            All Rights Reserved
          </p>
        </div>
        <div class="col-lg-6">
          <%= image_tag "td-banner.jpg", class: "img-responsive center-block" %>
        </div>
      </div>
    </div>
  </footer>

app/views/pages/_useful_links.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Links</h3>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to "Help Page", help_path, target: "_BLANK" %>
    </p>
    <p>
      <a href="http://ottawajazzfestival.com" target="_BLANK">Official Ottawa Jazz Festival website</a>
    </p>
    <p>
      <a href="http://ottawajazzfestival.com/faqs" target="_BLANK">Official Ottawa Jazz Festival FAQs</a>
    </p>
    <p>
      <%= link_to "Volunteer Code Of Conduct", codeofconduct_path, target: "_BLANK" %>.
    </p>
    <p>
      <a href="http://smartserve.ca/online-training-guidelines" target="_BLANK">Smart Serve Training</a>
    </p>
    <p>
      <a href="http://ottawa.ca/en/city-hall/get-know-your-city/volunteering/accessibility-training" target="_BLANK">
        Accessibility Training
      </a>
    </p>
  </div>
</div>

app/views/pages/about.html.erb
<h2>About Jazzify</h2>
<div class="row">
  <div class="col-md-6">
    <blockquote>
      I created the Ottawa Jazzify web application to modernize
      the volunteer application process at the Ottawa Jazz Festival.<br/>
      This project is made up of 100% volunteer work and does not
      cost the Festival a penny to operate.
      <footer>Sean Floyd</footer>
    </blockquote>
    <%= render 'pages/useful_links' %>
  </div>
  <div class="col-md-6">
    <div id="carousel-example-generic" class="carousel slide about-carousel-max-size center-block" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        <li data-target="#carousel-example-generic" data-slide-to="5"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag "Volunteers-2015_BrianGoldschmied-1024x575.jpg", class: "img-reponsive" %>
          <div class="carousel-caption">
            Photo by Brian Goldschmied
          </div>
        </div>
        <div class="item">
          <%= image_tag "Unknown.jpg", class: "img-responsive" %>
        </div>
        <div class="item">
          <%= image_tag "Unknown-2.jpg", class: "img-responsive" %>
        </div>
        <div class="item">
          <%= image_tag "Unknown-3.jpg", class: "img-responsive" %>
        </div>
        <div class="item">
          <%= image_tag "Unknown-4.jpg", class: "img-responsive" %>
        </div>
        <div class="item">
          <%= image_tag "Unknown-5.jpg", class: "img-responsive" %>
        </div>
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-6">
    <p>
      Created, designed and maintained by
      <a href="http://seanlf.github.io/web/" target="_BLANK">Sean Floyd</a> for the Ottawa Jazz Festival.
    </p>
    <p>Special thanks to Wendy Bardach, Casey Li, and Julian Nadeau.</p>
    <p>
      Proudly built with <a href="http://rubyonrails.org/" target="_BLANK">Ruby on Rails</a>.
    </p>
  </div>
</div>

app/views/pages/code_of_conduct.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Volunteer Code of Conduct</div>
    <div class="panel-body">
      <p>
        <strong>Prior to applying as a volunteer, it's important for you to know what you're signing up for!</strong>
      </p>

      <p>
        As volunteer for the Ottawa Jazz Festival, I agree to the following:
        <ul>
          <li>I will be a responsible ambassador for the Festival and represent the Festival in a positive way;</li>
          <li>I will be respectful of festival goers;</li>
          <li>I will work with other volunteers, performers, and staff in a positive manner;</li>
          <li>I will fulfill all volunteer responsibilities (i.e., the tasks assigned of me & the minimum time commitment required);</li>
          <li>I will maintain confidentiality with respect to all Ottawa Jazz Festival information and records</li>
          <li>I will not record any  festival performances (audio/video);</li>
          <li>I will not reserve seating in any of the audience areas until after the gate opens;</li>
          <li>I will leave my pets at home;</li>
          <li>I acknowledge my position of trust and will not use for my own advantage any money, information, or properties belonging to the Festival, its sponsors, artists, or vendors;</li>
          <li>I understand that if I consume alcohol while off duty, I am expected to drink responsibly and ensure that any clothing or credentials which identify me as a volunteer be removed;</li>
        </ul>
      </p>

      <p>
        I also understand that the Ottawa Jazz Festival has the right to immediately dismiss me as a volunteer for any of the following reasons:
          <ul>
            <li>If I display inappropriate behaviour or negative attitude;</li>
            <li>If I commit illegal, violent or unsafe acts;</li>
            <li>If I attempt to bring alcohol onto the site;</li>
            <li>If I use or possess illegal substances on site; or</li>
            <li>If I consume or am under the influence of alcohol or drugs while on duty.</li>
          </ul>
      </p>
      <strong>Failure to adhere to the Code of Conduct may result in disciplinary procedures or immediate loss of your volunteer standing for the current and future years.</strong>
    </div>
  </div>
</div>

app/views/pages/help.html.erb
<h1>Help Page</h1>
<hr>
<div class="row">
  <div class="col-md-6 col-md-push-6">
    <h2>Contact Us</h2>
    <div class="panel panel-default">
      <div class="panel-body">
        <p id="email_us_para">
          If you're emailing us about an issue you're experiencing, please include the steps you've taken to resolve it and results. If you have signed up, the email address you used.
        </p>
        <a href="mailto:ottawajazzify@gmail.com" class="btn btn-default btn-lg" id="email_us">Email us</a>
        <h4>
          <small>The person receiving these emails is a volunteer and the creator of this website.</small>
        </h4>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-md-pull-6">
    <%= render 'pages/faq' %>
  </div>
</div>

<style media="screen">
  p#email_us_para {
    font-size: 17px;
  }

</style>

app/views/pages/home.html.erb
<div class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">
          <%= image_tag "2016-ottawa-jazz-fest-dates.png", class: "img-responsive center-block" %>
          <h3>Volunteer at the Ottawa Jazz Festival.</h3>
          <hr class="intro-divider">
          <ul class="list-inline intro-social-buttons">
            <li>
              <%= link_to "Volunteer Positions", volunteer_positions_path, class: 'btn btn-default btn-lg' %>
            </li>
            <% if user_signed_in? %>
              <li>
                <% if current_user.user_application.nil? %>
                  <%= link_to new_user_application_path, class: 'btn btn-success btn-lg' do %>
                    <span class="network-name">Apply</span>
                  <% end %>
                <% else %>
                  <%= link_to view_user_applications_path(current_user.user_application), class: 'btn btn-success btn-lg' do %>
                    <span class="network-name">My Application</span>
                  <% end %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-lg' do %>
                  <span class="network-name">Logout</span>
                <% end %>
              </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-success btn-lg'  %></li>
              <li><%= link_to "Sign in", new_user_session_path, :class => 'btn btn-primary btn-lg'  %></li>
            <% end %>
          </ul>
          <hr class="intro-divider">
          <h5><%= 'Applicant'.pluralize(@number_of_applicants) %> to date: <%= @number_of_applicants %></h5>
        </div>
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /.intro-header -->
<!-- Page Content -->
<div class="content-section-a" id="first">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Ottawa Jazz Festival</h2>
        <p class="lead">
          The Ottawa International Jazz Festival is a celebration of the worlds best jazz artists each
          summer in the heart of downtown Ottawa.
          <br/>
          <br/>
          <a href="http://ottawajazzfestival.com/" target="_BLANK" class="btn btn-default"><i class="fa fa-building-o">&nbsp;</i>Official Website</a>
        </p>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6">
        <div id="carousel-example-generic"
          class="carousel slide about-carousel-max-size center-block img-thumbnail"
          data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            <li data-target="#carousel-example-generic" data-slide-to="5"></li>
          </ol>
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <%= image_tag "Volunteers-2013-arms-waving_scaled.jpg", class: "img-reponsive" %>
              <div class="carousel-caption">
                Photo by Brian Goldschmied
              </div>
            </div>
            <div class="item">
              <%= image_tag "Unknown.jpg", class: "img-responsive" %>
            </div>
            <div class="item">
              <%= image_tag "Unknown-2.jpg", class: "img-responsive" %>
            </div>
            <div class="item">
              <%= image_tag "Unknown-3.jpg", class: "img-responsive" %>
            </div>
            <div class="item">
              <%= image_tag "Unknown-4.jpg", class: "img-responsive" %>
            </div>
            <div class="item">
              <%= image_tag "Unknown-5.jpg", class: "img-responsive" %>
            </div>
          </div>
          <!-- Controls -->
          <a class="left carousel-control"
            href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control"
            href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /.content-section-a -->
<div class="content-section-b">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading"><i class='fa fa-calendar'>&nbsp;</i>Dates</h2>
        <p class="lead">
          We need volunteers starting from<br/>
          <u><%= Date.parse(@festivalStartDate).strftime('%A, %-d %B') %></u> to<br/>
          <u><%= Date.parse(@festivalEndDate).strftime('%A, %-d %B %Y') %></u>.
        </p>
      </div>
      <div class="col-lg-5 col-sm-pull-6  col-sm-6">
        <%= image_tag "2016-ottawa-jazz-fest-dates copy.png", class: "img-responsive img-thumbnail" %>
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /.content-section-b -->
<div class="content-section-a">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading"><i class='fa fa-location-arrow'>&nbsp;</i>Location</h2>
        <p class="lead">
          You can find maps on the official Ottawa Jazz Festival website.
          <br/>
          <br/>
          <a href="http://ottawajazzfestival.com/map" class="btn btn-default" target="_BLANK">
            <i class='fa fa-map-marker'>&nbsp;</i>
            Maps
          </a>
        </p>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6">
        <% #image_tag "phones.png", class: "img-responsive" %>
        <iframe src="https://mapsengine.google.com/map/embed?mid=zJSsAHwDnr1g.kS6cP1RqYa_Y" class="home-youtube-video img-thumbnail"></iframe>
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /.content-section-a -->
<div class="content-section-b">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading"><i class='fa fa-users'>&nbsp;</i>Lineup</h2>
        <p class="lead">
          Click on the button below to browse the schedule.
          <br/>
          <br/>
          <a href="http://ottawajazzfestival.com/schedule/" class="btn btn-default" target="_BLANK">Official schedule</a>
        </p>
      </div>
      <div class="col-lg-5 col-sm-pull-6 col-sm-6">
        <iframe src="https://www.youtube.com/embed/eqNasCEKT9s" class="embed-responsive-item img-thumbnail home-youtube-video"></iframe>
      </div>
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /.content-section-b -->
<%= render 'banner' %>
<!-- Footer -->
<%= render 'footer' %>

<script type="text/javascript">
  $(document).ready(prepareHomeEasterEgg);
</script>

app/views/pages/permissions.html.erb
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Jazzify Permissions</div>
  <div class="panel-body">
    <p>Here is a breakdown of all the permissions per role</p>
  </div>
	<table class="table table-hover table-striped table-bordered">
		<thead>
			<tr>
				<th></th>
				<th>Admin</th>
				<th>Moderator</th>
				<th>Registered User</th>
			</tr>
		</thead>
		<tbody>
			<% @permissions.each do |permission| %><tr>
				<td><%= permission[:name] %></td>
				<td><%= permission[:admin] %></td>
				<td><%= permission[:mod] %></td>
				<td><%= permission[:user] %></td></tr>
			<% end %>

		</tbody>

	</table>
</div>