config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :volunteer_position_contacts
  resources :user_informations, :concerns => :paginatable

  resources :user_applications, :concerns => :paginatable do
    collection do
      get 'success', action: :success
      get ':id/review', action: :review, as: :review
      get ':id/view', action: :view, as: :view
      post 'accept_or_deny', action: :accept_or_deny
      post 'reset/:id', action: :reset
    end
  end

  resources :volunteer_positions

  devise_for :users, controllers: {sessions: 'sessions'}

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Upmin::Engine => '/admin'
  end

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/permissions' => 'pages#permissions'
  get '/codeofconduct' => 'pages#code_of_conduct'
  get '/user_information/fake' => 'pages#fake_user_info'
  get '/privacypolicy' => 'pages#privacy'
  get '/help' => 'pages#help'

  # Two factor authentication routes
  get '/two_factor_authentication' => 'users#two_factor_authentication'
  get '/two_factor_authentication/configure' => 'users#setup_2fa'
  post '/two_factor_authentication/enable' => 'users#enable_2fa'
  post '/two_factor_authentication/disable' => 'users#disable_2fa'
  get '/two_factor_authentication/disable' => 'users#prepare_disable_2fa'

  # Reports routes
  get '/reports' => 'reports#index'
  get '/reports/export_user_applications'
  post '/reports/export_user_applications'
  get '/reports/position_popularity' => 'reports#position_picks'
  get '/reports/user_distribution' => 'reports#user_completion'
  get '/reports/t_shirt_distribution'
  get '/reports/user_sign_up_distribution'
  get '/reports/user_last_sign_in_at'
  get '/reports/volunteer_application_comments', concerns: :paginatable
  get '/reports/volunteer_application_comments_export'

end

app/models/user_application.rb
class UserApplication < ActiveRecord::Base
	belongs_to :user, class_name: User, primary_key: "id", foreign_key: "user_id"
  belongs_to :first_choice_volunteer_position, class_name: VolunteerPosition, primary_key: "id", foreign_key: "first_choice_volunteer_position_id"
  belongs_to :second_choice_volunteer_position, class_name: VolunteerPosition, primary_key: "id", foreign_key: "second_choice_volunteer_position_id"
	belongs_to :third_choice_volunteer_position, class_name: VolunteerPosition, primary_key: "id", foreign_key: "third_choice_volunteer_position_id"
	belongs_to :user_application_status, class_name: UserApplicationStatus, primary_key: "id", foreign_key: "user_application_status_id"
  belongs_to :status_changed_by_user, class_name: User, primary_key: "id", foreign_key: "status_changed_by"
	before_create :set_default_status

	validates_uniqueness_of :user_id, message: "has already applied"
  validate :choices_distinct?
  validates :first_choice_volunteer_position_id, :second_choice_volunteer_position_id, :third_choice_volunteer_position_id, presence: true

  def self.data_for_index
    self.joins(:user, user: :user_information)
    .joins(:user_application_status).joins(:first_choice_volunteer_position).joins(:second_choice_volunteer_position).joins(:third_choice_volunteer_position)
    .order(created_at: :desc)
    .select(:id, :created_at, :status, "concat(user_informations.first_name, ' ', user_informations.last_name) AS name", 'volunteer_positions.name AS first_choice', 'second_choice_volunteer_positions_user_applications.name AS second_choice', 'third_choice_volunteer_positions_user_applications.name AS third_choice')
  end

  def self.export
    self.joins(:user, user: :user_information)
    .joins(:user_application_status)
    .joins(:first_choice_volunteer_position)
    .joins(:second_choice_volunteer_position)
    .joins(:third_choice_volunteer_position)
    .select(:first_name, :last_name, :address, :city, :province, :postal_code, :home_phone_number, :work_phone_number, :cell_phone_number, :email, :t_shirt_size, :age_group, :emergency_contact_name, :emergency_contact_number, :notes, :availability, 'volunteer_positions.name AS first_choice', 'second_choice_volunteer_positions_user_applications.name AS second_choice', 'third_choice_volunteer_positions_user_applications.name AS third_choice')
  end

  def self.export_for_position(volunteer_position_id, choice)
    self.export.where("#{choice}_choice_volunteer_position_id = ?", volunteer_position_id)
  end

  def self.comments_report
    self.joins(:user, user: :user_information).joins(:first_choice_volunteer_position).joins(:second_choice_volunteer_position).joins(:third_choice_volunteer_position).order(created_at: :desc).select(:id, :first_name, :last_name, 'volunteer_positions.name AS choice1', 'second_choice_volunteer_positions_user_applications.name AS choice2', 'third_choice_volunteer_positions_user_applications.name AS choice3', :coordinator_notes)
  end

  private
	def set_default_status
      self.user_application_status = UserApplicationStatus.find_by({status: 'Pending'})
	end

  def choices_distinct?
    if self.first_choice_volunteer_position_id == self.second_choice_volunteer_position_id or self.first_choice_volunteer_position_id == self.third_choice_volunteer_position_id or self.second_choice_volunteer_position_id == self.third_choice_volunteer_position_id
        errors.add :base, "You must select three distinct choices."
    end
  end
end

app/controllers/user_applications_controller.rb
class UserApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_user_application, except: [:new, :create]
  before_action :set_user_applications, only: :index
  before_action :set_volunteer_positions
  before_action :set_user_application_statuses, except: [:destroy]
  before_action :application_locked?, only: [:edit, :update, :destroy]
  after_action :verify_authorized, except: :index
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized
  respond_to :html, :json

  # Show all user applications
  def index
    # If the user is not elevated, redirect to their application
    if !@user.is_elevated?
      registered_user_application = UserApplication.find_by(user_id: @user.id)
      if registered_user_application.nil?
        redirect_to new_user_application_path
      else
        redirect_to user_application_url registered_user_application.id
      end
    else
      authorize @user_applications
      @vpc = VolunteerPositionContact.find_by(user_id: @user.id)
      if @vpc and @vpc.volunteer_position_id
        @vp = @vpc.volunteer_position_id
      end
      @count = UserApplication.count
      respond_with(@user_applications)
    end
  end

  # Apply to position page
  def new
    flash[:notice] = 'Due to an overwhelming response, we are running out of positions to fill. You may still apply, but doing so will add you to our waiting list. You will only be contacted if a position opens up and you are its next candidate.'
    @user_information = UserInformation.find_by(user_id: @user.id)
    new_user_application
    authorize @user_application
    if @user_information.nil?
      # Verify that the user has a user information
      session[:return_to] = new_user_application_url
      redirect_to new_user_information_url and return
    elsif UserApplication.find_by(user_id: @user.id).nil?
      # Verify that the user hasn't already applied
      respond_with @user_application
    else
      @user_application = UserApplication.find_by(user_id: @user.id)
      respond_with(@user_application)
    end
  end

  # Show an application
  def show
    authorize @user_application
    get_application_volunteer_choices
    respond_with(@user_application)
  end

  # Confirmation of the application
  def create
    @user_application = UserApplication.new(user_application_params)
    authorize @user_application
    if @user_application.save and @user_application.user_id == @user.id
      Thread.new do
        notify_admins_link('New Jazzify Application', @user.user_information.full_name + " has applied", view_user_applications_path(@user_application))
      end
      redirect_to success_user_applications_path
    else
      respond_with(@user_application)
    end
  end

  # Edit an application
  def edit
    authorize @user_application
  end

  # Submit edited changes
  def update
    @user_application = UserApplication.find(params[:id])
    @user_application.attributes = user_application_params
    authorize @user_application

    if @user_application.update(user_application_params) and @user_application.user_id == @user.id
      redirect_to success_user_applications_path
    else
      respond_with(@user_application)
    end
  end

  # Delete application
  def destroy
    authorize @user_application
    @user_application.destroy
    respond_with(@user_application)
  end

  # View application
  def view
    @user_application = UserApplication.find(params[:id])
    authorize @user_application
    @user_information = @user_application.user.user_information
    @time = (@user_application.created_at + 24.hours)
  end

  def review
    @user_application = UserApplication.find(params[:id])
    authorize @user_application
    @user_information = @user_application.user.user_information
  end

  # Accept or deny application
  def accept_or_deny
    @user_application = UserApplication.find(params['user_application_id'])
    authorize @user_application
    status = params['accept_or_deny']
    @user_application.coordinator_notes = params['coordinator_notes']
    change_status(status, "Application #{status.downcase} successfully")
  end

  # Reset application status to pending
  def reset
    @user_application = UserApplication.find(params['id'])
    authorize @user_application
    @user_application.coordinator_notes = nil
    change_status("Pending", "Application status reset successfully")
  end

  # Success page after applying
  def success
    @user_application = UserApplication.find_by(user_id: @user.id)
    authorize @user_application
    @time = (@user_application.created_at + 24.hours)
  end

  # Private methods
  private
  def set_user_application
    if ! params[:id].nil?
      @user_application = UserApplication.find(params[:id])
    else
      @user_application = UserApplication.new
      @user_application.user = @user
    end
  end

  def set_user_applications
    @user_applications = UserApplication.data_for_index.page params[:page]
    @count = @user_applications.length
  end

  def set_volunteer_positions
    if @user and @user.is_elevated?
      @volunteer_positions = VolunteerPosition.all.order(:name)
    else
      @volunteer_positions = VolunteerPosition.visible.order(:name)
    end
  end

  # Define params that are permitted when submitting a request to this resource.
  def user_application_params
    params.require(:user_application).permit(:user_id, :user_application_status_id, :first_choice_volunteer_position_id, :second_choice_volunteer_position_id, :third_choice_volunteer_position_id)
  end

  def set_user_application_statuses
    if @user.is_elevated?
      return @user_application_statuses = UserApplicationStatus.all.order(:status)
    else
      return @user_application_statuses = UserApplicationStatus.find_by(status: 'Pending')
    end
  end

  def new_user_application
    @user_application = UserApplication.new
    @user_application.user_id = @user.id
    @user_application.user_application_status_id = UserApplicationStatus.find_by(status: 'Pending').id
  end

  def not_authorized
    redirect_to user_applications_url, alert: 'You are not authorized to perform the requested action!'
  end

  def get_application_volunteer_choices
    @first_choice_volunteer_position = VolunteerPosition.find(@user_application.first_choice_volunteer_position_id) unless @user_application.first_choice_volunteer_position_id.nil?
    @second_choice_volunteer_position = VolunteerPosition.find(@user_application.second_choice_volunteer_position_id) unless @user_application.second_choice_volunteer_position_id.nil?
    @third_choice_volunteer_position = VolunteerPosition.find(@user_application.third_choice_volunteer_position_id) unless @user_application.third_choice_volunteer_position_id.nil?
  end

  # Change application status.
  def change_status(status, message)
    @user_application.user_application_status_id = UserApplicationStatus.find_by(status: status).id
    @user_application.status_changed_by = @user.id

    if @user_application.save
      redirect_to user_applications_path, alert: message
    end
  end
end

app/helpers/user_applications_helper.rb
module UserApplicationsHelper
end

app/views/user_applications/_form.html.erb
<%= form_for(@user_application, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @user_application.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Please fix the following <%= pluralize(@user_application.errors.count, "error") %>:</h4>

      <ul>
      <% @user_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group hidden">
    <%= f.label :user_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.hidden_field :user_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group hidden">
    <%= f.label :user_application_status_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.hidden_field :user_application_status_id, :class => "form-control" %>
    </div>
  </div>
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Position Name</th>
        <th>First Choice</th>
        <th>Second Choice</th>
        <th>Third Choice</th>
      </tr>
    </thead>
    <tbody class="striped-rows table-hover">
      <% @volunteer_positions.each do |volunteer_position| %>
        <tr>
          <td><%= link_to volunteer_position.name, volunteer_position_url(volunteer_position.id), target: '_BLANK' %></td>
          <td><%= f.radio_button :first_choice_volunteer_position_id, volunteer_position.id %></td>
          <td><%= f.radio_button :second_choice_volunteer_position_id, volunteer_position.id %></td>
          <td><%= f.radio_button :third_choice_volunteer_position_id, volunteer_position.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

<!-- if application position is equal to current in iteration, add select -->

app/views/user_applications/_view_application_add_comment.html.erb
<!-- Modal -->
<div class="modal fade" id="add_comment_for_user_application" tabindex="-1" role="dialog" aria-labelledby="add_comment_for_user_application_title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="add_comment_for_user_application_title">Title</h4>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="form-group">
            <%= label_tag(:coordinator_notes, "Comments", class: "control-label") %>
            <%= text_area_tag(:coordinator_notes, comments, class: "form-control") %>
          </div>
        </div></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" name="commit" class="btn" id="button_submit"></button>
        </div>
      </div>
    </div>
  </div>

app/views/user_applications/edit.html.erb
<% if @user_elevated %>
  <%= link_to user_applications_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
<% end %>

<%= link_to @user_application, :class => 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-info-sign"></span>
  Show
<% end %>

<h1>Editing
  <% if @user_application.user_id == @user.id %>
    my
  <% else %>
    user
  <% end %>
   application
</h1>

<%= render 'form' %>

app/views/user_applications/index.html.erb
<h1>Volunteer Applications</h1>
<% if @user_applications.nil? or @count == 0 %>

  <h3>No one has applied yet. <i class="fa fa-frown-o">&nbsp;</i></h3>

<% else %>
  <% if @user.is_elevated? %>
    <% if @user.is_admin? %>
      <%= link_to "Export all", reports_export_user_applications_path, class: "btn btn-default" %>
      <a href="#" data-toggle="modal" data-target="#export_user_applications_for_position" class="btn btn-default">
        Export for specific position
      </a>
      <span class="pull-right">Count: <%= @count %></span>
      <%= render 'reports/export_applications' %>
    <% end %>
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>First choice</th>
          <th>Second choice</th>
          <th>Third choice</th>
          <th>Status</th>
          <th>Applied</th>
          <th></th>
          <% if current_user.is_admin? %>
          <th></th>
          <th></th>
          <% end %>
        </tr>
      </thead>

      <tbody>

        <%= content_tag_for(:tr, @user_applications) do |user_application| %>
          <td><%= user_application.name %></td>
          <td><%= user_application.first_choice %></td>
          <td><%= user_application.second_choice %></td>
          <td><%= user_application.third_choice %></td>
          <td><%= user_application.status %></td>
          <td><%= user_application.created_at.to_formatted_s(:long) %></td>
          <td><%= link_to 'Review', review_user_applications_path(user_application.id) %></td>
          <% if current_user.is_admin? %>
          <td><%= link_to "Edit", edit_user_application_path(user_application) %></td>
          <td><%= link_to 'Delete', user_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

        <% end %>

      </tbody>
    </table>
  </div>
  <%= paginate @user_applications %>

<% end %>

app/views/user_applications/new.html.erb
<div class="row">
  <div class="col-md-3 col-md-push-9">
    <%= image_tag "OJF_logo_2015-olg copy.png", class: "img-responsive center-block" %>
  </div>
  <div class="col-md-9 col-md-pull-3">
    <h1>
      Apply<br/>
      <small>Select three distinct choices.</small>
    </h1>
  </div>
</div>
<br/>
<%= render 'form' %>

app/views/user_applications/review.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3 application-div">
      <h3>Contact Information</h3>
      <div class="form-group">
        <label class="control-label">Name</label>
        <p class="well well-sm" name="user_information[Name]">
          <%= "#{@user_information.first_name} #{@user_information.last_name}" %>
        </p>
      </div>
      <div class="form-group">
        <label class="control-label">City</label>
        <p class="well well-sm" name="user_information[City]">
          <%= @user_information.city %>
        </p>
      </div>
      <div class="form-group">
        <label class="control-label">Province</label>
        <p class="well well-sm" name="user_information[Province]">
          <%= @user_information.province %>
        </p>
      </div>
      <% unless @user_information.home_phone_number.empty? %>
      <div class="form-group">
        <label class="control-label">Home phone number</label>
        <p class="well well-sm" name="user_information[Home phone number]">
          <%= @user_information.home_phone_number %>
        </p>
      </div>
      <% end %>
      <% unless @user_information.work_phone_number.empty? %>
      <div class="form-group">
        <label class="control-label">Work phone number</label>
        <p class="well well-sm" name="user_information[Work phone number]">
          <%= @user_information.work_phone_number %>
        </p>
      </div>
      <% end %>
      <% unless @user_information.cell_phone_number.empty? %>
      <div class="form-group">
        <label class="control-label">Cell phone number</label>
        <p class="well well-sm" name="user_information[Cell phone number]">
          <%= @user_information.cell_phone_number %>
        </p>
      </div>
      <% end %>
      <div class="form-group">
        <label class="control-label">Email</label>
        <p class="well well-sm" name="user[Email]">
          <%= @user_information.user.email %>
        </p>
      </div>
    </div>
    <div class="col-sm-4 col-sm-offset-1 application-div">
      <h3>Jazz specific Information</h3>
      <div class="form-group">
        <label class="control-label">Age group</label>
        <p class="well well-sm" name="user_information[Age group]">
          <%= @user_information.age_group %>
        </p>
      </div>
      <div class="form-group">
        <label class="control-label">Notes</label>
        <p class="well well-sm" name="user_information[Notes]">
          <%= @user_information.notes %>
        </p>
      </div>
      <div class="form-group">
        <label class="control-label">Availability</label>
        <p class="well well-sm" name="user_information[Availability]">
          <%= @user_information.availability %>
        </p>
      </div>
    </div>
    <div class="col-sm-3 col-sm-offset-1 application-div">
      <h3>Choices</h3>
      <div class="form-group">
        <label class="control-label">#1</label>
        <p class="well well-sm" name="user_application[First Choice]">
          <%= @user_application.first_choice_volunteer_position.name %>
        </p>
      </div>
      <div class="form-group">
        <label class="control-label">#2</label>
        <p class="well well-sm" name="user_application[Second Choice]">
          <%= @user_application.second_choice_volunteer_position.name %>
        </p>
      </div>
      <div class="form-group">
        <label class="control-label">#3</label>
        <p class="well well-sm" name="user_application[Third Choice]">
          <%= @user_application.third_choice_volunteer_position.name %>
        </p>
      </div>
    </div>
    <div class="col-sm-4 col-sm-offset-1 application-div">
      <h5>Accept or Deny Application</h5>
      <p class="home-buttons">
        <%= form_tag(accept_or_deny_user_applications_path) do |f| %>
        <%= hidden_field_tag(:user_application_id, @user_application.id) %>
        <input type="hidden" id="accept_or_deny" name="accept_or_deny"/>
        <%= render "view_application_add_comment", comments: @user_application.coordinator_notes %>
        <% submit_tag("Export Applications", class: 'btn btn-primary') %>
        <a href="#Accept" class="btn btn-success" data-toggle="modal" data-target="#add_comment_for_user_application" data-type="Accept" id="accept">Accept</a>
        <a href="#Deny" class="btn btn-danger" data-toggle="modal" data-target="#add_comment_for_user_application" data-type="Deny" id="deny">Deny</a>
        <%= link_to "Reset to Pending", "/user_applications/reset/#{@user_application.id}", method: :post, id:"reset", class: "btn btn-primary" %>
        <% end %>
      </p>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('#add_comment_for_user_application').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var type = button.data('type') // Extract info from data-* attributes
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var modal = $(this)
    modal.find('.modal-title').text(type + " Application")
    $("#button_submit").text(type)
    if(type == "Accept"){
      $("#button_submit").removeClass('btn-danger').addClass('btn-success')
      $("#accept_or_deny").val("Accepted")
    }else{
      $("#button_submit").removeClass('btn-success').addClass('btn-danger')
      $("#accept_or_deny").val("Denied")
    }
  });
  $(function() {
    var status = "<%= @user_application.user_application_status.status %>"
    if(status == "Accepted"){
      $("#accept").attr('disabled', true)
    }
    else if(status == "Denied"){
      $("#deny").attr('disabled', true)
    }
    else{
      $("#reset").attr('disabled', true)
    }
  });

</script>

app/views/user_applications/show.html.erb
<h1>
  <% if @user_application.user_id == @user.id %> My <% end %>
  Application
</h1>

<div class="panel-body">
  <form class="form-horizontal">


    <div class="form-group">
      <label class="col-sm-2 control-label">Application status</label>
      <div class="col-sm-10">
        <div class="well well-sm" name="user_application[User application status]">
          <%= simple_format(@user_application.user_application_status.status) %>
        </div>
      </div>
    </div>


    <div class="form-group">
      <label class="col-sm-2 control-label">First Choice</label>
      <div class="col-sm-10">
        <div class="well well-sm" name="user_application[Volunteer position]">
          <%= simple_format(@first_choice_volunteer_position.name) %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Second Choice</label>
      <div class="col-sm-10">
        <div class="well well-sm" name="user_application[Volunteer position]">
          <%= simple_format(@second_choice_volunteer_position.name) %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Third Choice</label>
      <div class="col-sm-10">
        <div class="well well-sm" name="user_application[Volunteer position]">
          <%= simple_format(@third_choice_volunteer_position.name) %>
        </div>
      </div>
    </div>

  </form>
</div>

<div class="" role="group" aria-label="...">
  <%= link_to user_applications_path, :class => 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
  <% end %>
  <% if policy(@user_application).edit? %>
    <%= link_to edit_user_application_path(@user_application), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
    <% end %>
  <% end %>
  <% if policy(@user_application).destroy? %>
  <%= link_to 'Delete', @user_application, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
  <% end %>
</div>
</div>

app/views/user_applications/success.html.erb
<div class="jumbotron container">
  <div class="row">
    <div class="col-sm-3 col-sm-push-9">
    <div class="ojf-logo-success img-circle">
      <%= image_tag "OJF_logo_2015.png", class: "img-responsive center-block", style: "margin:auto; padding: 10px;" %>
    </div></div>
    <div class="col-sm-9 col-sm-pull-3">
      <h2>Your application was successful</h2>
    </div>
  </div>
  <p>
    Thank you for your interest in volunteering with us. We'll get back to you as soon as possible!
  </p>
  <p>
    <% if DateTime.now < @time %>
    You have until
    <strong class="fa fa-clock-o"></strong> <u><%= @time.to_formatted_s(:long) %></u>
    to edit any submitted information before it's sent to a volunteer coordinator.
    <i style="font-size:15px!important">If you require any changes to be made after your application is locked, please contact a coordinator.</i>
    <br/>
    To edit your application, click <%= link_to "here", edit_user_application_path(@user_application.id) %>.
    <% else %>
    Your application has been sent to a volunteer coordinator. If you need to change something, please contact them <a href="mailto:ottawajazzifycoordinator@gmail.com">here</a>.
    <% end %>
  </p>
  <hr/>
  <p>
    We'd be thrilled if you took this quick anonymous survey on the application process.
    <br/>
    <br/>
    <a class="typeform-share link btn btn-success" href="https://jazzify.typeform.com/to/B27JqP"
      data-mode="1" target="_blank">
      Survey
    </a>
    <script>
    (function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,
    id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';
    if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';
    q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()
    </script>
  </p>
</div>