config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :volunteer_position_contacts
  resources :user_informations, :concerns => :paginatable

  resources :user_applications, :concerns => :paginatable do
    collection do
      get 'success', action: :success
      get ':id/review', action: :review, as: :review
      get ':id/view', action: :view, as: :view
      post 'accept_or_deny', action: :accept_or_deny
      post 'reset/:id', action: :reset
    end
  end

  resources :volunteer_positions

  devise_for :users, controllers: {sessions: 'sessions'}

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Upmin::Engine => '/admin'
  end

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/permissions' => 'pages#permissions'
  get '/codeofconduct' => 'pages#code_of_conduct'
  get '/user_information/fake' => 'pages#fake_user_info'
  get '/privacypolicy' => 'pages#privacy'
  get '/help' => 'pages#help'

  # Two factor authentication routes
  get '/two_factor_authentication' => 'users#two_factor_authentication'
  get '/two_factor_authentication/configure' => 'users#setup_2fa'
  post '/two_factor_authentication/enable' => 'users#enable_2fa'
  post '/two_factor_authentication/disable' => 'users#disable_2fa'
  get '/two_factor_authentication/disable' => 'users#prepare_disable_2fa'

  # Reports routes
  get '/reports' => 'reports#index'
  get '/reports/export_user_applications'
  post '/reports/export_user_applications'
  get '/reports/position_popularity' => 'reports#position_picks'
  get '/reports/user_distribution' => 'reports#user_completion'
  get '/reports/t_shirt_distribution'
  get '/reports/user_sign_up_distribution'
  get '/reports/user_last_sign_in_at'
  get '/reports/volunteer_application_comments', concerns: :paginatable
  get '/reports/volunteer_application_comments_export'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  require 'axlsx'

  before_filter :authenticate_user!
  before_action :restrict_to_elevated
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  def export_user_applications
    title = ''
    xlsx = Axlsx::Package.new do |p|
      p.workbook.add_worksheet(name: "User Applications") do |sheet|
        p.use_shared_strings = true

        # Headers
        sheet.add_row get_user_application_export_headers

        # Get data
        if params[:volunteer_position]
          volunteer_position_id = params[:volunteer_position][:id].to_i
          applications = UserApplication.export_for_position(volunteer_position_id, params[:choice])
          title = "Applications for #{VolunteerPosition.find(volunteer_position_id).name}"
        else
          applications = UserApplication.export
          title = "Applications"
        end

        # Export
        add_data_to_sheet_for_export_applications(sheet, applications)
      end
    end
    xlsx.serialize("/tmp/#{title}.xlsx")
    send_file("/tmp/#{title}.xlsx")
  end

  # Line chart for volunteer position picks
  def position_picks

    # Get data
    all_applications = UserApplication.all
    positions_applied_for = VolunteerPosition.positions_applied_for.order(:name)

    # Initialize hashes
    initialize_hash_for_position_picks_chart(all_applications, positions_applied_for)
  end

  # bar plot how many users have registered, completed info, and applied
  def user_completion
    @users = User.all.count
    @infos = UserInformation.all.count
    @apps = UserApplication.all.count
  end

  # doughnut chart: distribution of t shirt sizes
  def t_shirt_distribution
    accepted = UserApplicationStatus.find_by(status: "Accepted").id
    # get all accepted application users
    accepted_application_users =
      UserApplication.where(user_application_status_id: accepted).pluck(:user_id)
    infos = UserInformation.where(user_id: accepted_application_users)
    @sizes = infos.uniq.pluck(:t_shirt_size)
    @distribution = {}
    @sizes.each do |size|
      count = infos.where("t_shirt_size = ?", size).count
      @distribution[size] = count
    end
  end

  # Line chart showing frequency of users logged in during time frames
  def user_last_sign_in_at
    @labels = [], @datapoints = []
    values = User.where('last_sign_in_at IS NOT NULL').group('month, year').order('year, month').pluck('EXTRACT(MONTH FROM current_sign_in_at) as month, EXTRACT(YEAR FROM current_sign_in_at) as year, COUNT(current_sign_in_at)')
    @labels = values.map { |v| "#{Date::MONTHNAMES[v[0]]} #{v[1].round}" }
    @datapoints = values.map { |v| v[2] }
    @number_of_users = User.count
  end

  def user_sign_up_distribution
    @months = User.pluck("date_trunc('month',DATE(created_at))").sort
    @month_names = []
    @month_counts = {}
    @months.uniq.each_with_index do |date, index|
      @month_names[index] = "#{Date::MONTHNAMES[date.month]} #{date.year}"
      @month_counts[@month_names[index]] = @months.count(date)
    end
  end

  # HTML table containing the name, choices and coordinator comments
  def volunteer_application_comments
    @rows = UserApplication.comments_report.page(params[:page])
  end

  def volunteer_application_comments_export
    title = String.new
    xlsx = Axlsx::Package.new do |p|
      p.workbook.add_worksheet(name: "User Application Comments") do |sheet|
        p.use_shared_strings = true

        # Headers
        sheet.add_row ['Name', 'Choices', 'Comments']

        # Get data
        volunteer_application_comments = UserApplication.comments_report
        title = "Application comments"

        # Export
        volunteer_application_comments.each { |row| sheet.add_row [[row.first_name, row.last_name].join(' '), [row.choice1, row.choice2, row.choice3].join(', '), row.coordinator_notes] }
      end
    end
    xlsx.serialize("/tmp/#{title}.xlsx")
    send_file("/tmp/#{title}.xlsx")
  end

  private

  def get_user_application_export_headers
    return ['First Name', 'Last Name', 'Address', 'City',
            'Province', 'Postal Code', 'Home Phone Number', 'Work Phone Number',
            'Cell Phone Number', 'Email', 'T Shirt Size', 'Age Group',
            'Emergency Contact Name', 'Emergency Contact Number', 'Notes', 'Availability',
            'First Choice', 'Second Choice', 'Third Choice', 'Classification']
  end

  def initialize_hash_for_position_picks_chart(all_applications, positions_applied_for)
    @x = {first_choice_volunteer_position_id: "First Choice", second_choice_volunteer_position_id: "Second Choice", third_choice_volunteer_position_id: "Third Choice"}
    @choices = {}
    @x.each do |num|
      @choices[num[1]] = {}
      positions_applied_for.each do |position|
        @choices[num[1]]["#{position.name}"] = all_applications.where(num[0] => position.id.to_s).count
      end
    end
  end

  def add_data_to_sheet_for_export_applications(sheet, rows)
    rows.each do |row|
      sheet.add_row  [
        row.first_name,
        row.last_name,
        row.address,
        row.city,
        row.province,
        row.postal_code.gsub(/[- ]/,''),
        row.home_phone_number.gsub(/[()-. ]/,''),
        row.work_phone_number.gsub(/[()-. ]/,''),
        row.cell_phone_number.gsub(/[()-. ]/,''),
        row.email,
        row.t_shirt_size,
        row.age_group,
        row.emergency_contact_name,
        row.emergency_contact_number.gsub(/[()-. ]/,''),
        row.notes,
        row.availability,
        row.first_choice,
        row.second_choice,
        row.third_choice,
        'Volunteer'
      ]
    end
  end

  def get_counts_for_users_sign_in_report(one_week_where_clause, two_weeks_where_clause, under_a_month_where_clause, over_a_month_where_clause)
    @counts = {
      "One Week": User.where(one_week_where_clause).count,
      "Two Weeks": User.where(two_weeks_where_clause).count,
      "Under a month": User.where(under_a_month_where_clause).count,
      "Over a month": User.where(over_a_month_where_clause).count
    }
  end
end

app/views/reports/_export_applications.html.erb
<!-- Modal -->
<div class="modal fade" id="export_user_applications_for_position" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Export applications for position</h4>
      </div>
      <%= form_tag(reports_export_user_applications_path) do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <label>I want all applications that have:</label>
          <br/>
          <%= collection_select(:volunteer_position, :id, VolunteerPosition.positions_applied_for.order(:name), :id, :name) %>
        </div>

        <div class="form-group">
          <label>as the:</label>
          <ul class="list-unstyled">
          <li><label><input type="radio" checked id="first_choice" name="choice" value="first">&nbsp;first choice</label></li>
          <li><label><input type="radio" id="second_choice" name="choice" value="second">&nbsp;second choice</label></li>
          <li><label><input type="radio" id="third_choice" name="choice" value="third">&nbsp;third choice</label></li>
          </ul>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag("Export Applications", class: 'btn btn-primary') %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<h1>Reports</h1>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Excel Reports</h3>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <li>
            <%= link_to "Export all applications", reports_export_user_applications_path %>
          </li>
          <li>
            <a href="#" data-toggle="modal" data-target="#export_user_applications_for_position">
              Export applications for position
            </a>
          </li>
          <li>
            <%= link_to "Volunteer application comments", reports_volunteer_application_comments_path %>
          </li>
        </ul>
        <%= render 'export_applications', remote: true %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Charts</h3>
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <li>
            <%= link_to "Positition picks", reports_position_popularity_path %>
          </li>
          <li>
            <%= link_to "T shirt distribution", reports_t_shirt_distribution_path %>
          </li>
          <li>
            <%= link_to "User completion progress", reports_user_distribution_path %>
          </li>
          <li>
            <%= link_to "User sign up distribution", reports_user_sign_up_distribution_path %>
          </li>
          <li>
            <%= link_to "User last logged in", reports_user_last_sign_in_at_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">More</h3>
      </div>
      <div class="panel-body">
        <h5><small>Coming soon</small></h5>
      </div>
    </div>
  </div>
</div>

app/views/reports/position_picks.html.erb
<div class="row">
  <div class="col-md-2">
    <fieldset>
      <legend>Legend</legend>
      <ul style="padding-left: 0px; list-style-type: none">
        <li>
          <span style="background-color: rgba(150,220,0,0.2); width: 10px; border: 1px solid rgba(150,220,0,1)">&nbsp;&nbsp;&nbsp;&nbsp;</span> First Choice
        </li>
        <li>
          <span style="background-color: rgba(151,187,205,0.2); width: 10px; border: 1px solid rgba(151,187,205,1)">&nbsp;&nbsp;&nbsp;&nbsp;</span> Second Choice
        </li>
        <li>
          <span style="background-color: rgba(130,0,0,0.2); width: 10px; border: 1px solid rgba(130,0,0,1)">&nbsp;&nbsp;&nbsp;&nbsp;</span> Third Choice
        </li>
      </ul>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-10">
    <% unless @choices.first.last.empty? %>
      <canvas id="canvas"></canvas>
    <% else %>
      <h1>
        No one has applied yet.
      </h1>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var lineChartData = {
    labels: <%= raw @choices[@x.values[0]].keys.to_a %>,
    datasets: [
      {
        label: "<%= @x.values[0] %>",
        fillColor: "rgba(150,220,0,0.2)",
        strokeColor: "rgba(150,220,0,1)",
        pointColor: "rgba(150,220,0,1)",
        pointStrokeColor: "#fff",
        pointHighlightFill: "#fff",
        pointHighlightStroke: "rgba(220,220,220,1)",
        data: <%= @choices[@x.values[0]].values %>
      },
      {
        label: "<%= @x.values[1] %>",
        fillColor: "rgba(151,187,205,0.2)",
        strokeColor: "rgba(151,187,205,1)",
        pointColor: "rgba(151,187,205,1)",
        pointStrokeColor: "#fff",
        pointHighlightFill: "#fff",
        pointHighlightStroke: "rgba(220,220,220,1)",
        data: <%= @choices[@x.values[1]].values %>
      },
      {
        label: "<%= @x.values[2] %>",
        fillColor: "rgba(130,0,0,0.2)",
        strokeColor: "rgba(130,0,0,1)",
        pointColor: "rgba(130,0,0,1)",
        pointStrokeColor: "#fff",
        pointHighlightFill: "#fff",
        pointHighlightStroke: "rgba(220,220,220,1)",
        data: <%= @choices[@x.values[2]].values %>
      }
    ]
  };

    window.myRadar = new Chart(document.getElementById("canvas").getContext("2d")).Line(lineChartData, {
      responsive: true
    });
  });
</script>

app/views/reports/radar_chart_position_picks.html.erb
<div class="row">
  <div class="col-md-2">
    <fieldset>
      <legend>Legend</legend>
      <ul style="padding-left: 0px; list-style-type: none">
        <li>
          <span style="background-color: rgba(150,220,0,0.2); width: 10px; border: 1px solid rgba(150,220,0,1)">&nbsp;&nbsp;&nbsp;&nbsp;</span> First Choice
        </li>
        <li>
          <span style="background-color: rgba(151,187,205,0.2); width: 10px; border: 1px solid rgba(151,187,205,1)">&nbsp;&nbsp;&nbsp;&nbsp;</span> Second Choice
        </li>
        <li>
          <span style="background-color: rgba(130,0,0,0.2); width: 10px; border: 1px solid rgba(130,0,0,1)">&nbsp;&nbsp;&nbsp;&nbsp;</span> Third Choice
        </li>
      </ul>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-10">
    <canvas id="canvas"></canvas>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var radarChartData = {
    labels: <%= raw @choices[@x.values[0]].keys.to_a %>,
    datasets: [
      {
        label: "<%= @x.values[0] %>",
        fillColor: "rgba(150,220,0,0.2)",
        strokeColor: "rgba(150,220,0,1)",
        pointColor: "rgba(150,220,0,1)",
        pointStrokeColor: "#fff",
        pointHighlightFill: "#fff",
        pointHighlightStroke: "rgba(220,220,220,1)",
        data: <%= @choices[@x.values[0]].values %>
      },
      {
        label: "<%= @x.values[1] %>",
        fillColor: "rgba(151,187,205,0.2)",
        strokeColor: "rgba(151,187,205,1)",
        pointColor: "rgba(151,187,205,1)",
        pointStrokeColor: "#fff",
        pointHighlightFill: "#fff",
        pointHighlightStroke: "rgba(220,220,220,1)",
        data: <%= @choices[@x.values[1]].values %>
      },
      {
        label: "<%= @x.values[2] %>",
        fillColor: "rgba(130,0,0,0.2)",
        strokeColor: "rgba(130,0,0,1)",
        pointColor: "rgba(130,0,0,1)",
        pointStrokeColor: "#fff",
        pointHighlightFill: "#fff",
        pointHighlightStroke: "rgba(220,220,220,1)",
        data: <%= @choices[@x.values[2]].values %>
      }
    ]
  };

    window.myRadar = new Chart(document.getElementById("canvas").getContext("2d")).Radar(radarChartData, {
      responsive: true
    });
  });
</script>

app/views/reports/t_shirt_distribution.html.erb
<div class="row">
  <div class="col-md-2">
    <fieldset>
      <legend>Legend</legend>
      <ul style="padding-left: 0px; list-style-type: none">
        <li>
          <span style="background-color: #F7464A; width: 10px; border: 1px solid #FF5A5E">&nbsp;&nbsp;&nbsp;&nbsp;</span> Small<span class="text-right pull-right"><%= @distribution["Small"] %></span>
        </li>
        <li>
          <span style="background-color: #46BFBD; width: 10px; border: 1px solid #5AD3D1">&nbsp;&nbsp;&nbsp;&nbsp;</span> Medium<span class="text-right pull-right"><%= @distribution["Medium"] %></span>
        </li>
        <li>
          <span style="background-color: #FDB45C; width: 10px; border: 1px solid #FFC870">&nbsp;&nbsp;&nbsp;&nbsp;</span> Large<span class="text-right pull-right"><%= @distribution["Large"] %></span>
        </li>
        <li>
          <span style="background-color: #949FB1; width: 10px; border: 1px solid #A8B3C5">&nbsp;&nbsp;&nbsp;&nbsp;</span> XL<span class="text-right pull-right"><%= @distribution["XL"] %></span>
        </li>
        <li>
          <span style="background-color: #4D5360; width: 10px; border: 1px solid #616774">&nbsp;&nbsp;&nbsp;&nbsp;</span> XXL<span class="text-right pull-right"><%= @distribution["XXL"] %></span>
        </li>
        <li>
          <span style="background-color: #8D5360; width: 10px; border: 1px solid #616774">&nbsp;&nbsp;&nbsp;&nbsp;</span> XXXL<span class="text-right pull-right"><%= @distribution["XXXL"] %></span>
        </li>
        <hr/>
        <li>Total<span class="text-right pull-right"><%= @distribution.values.sum %></span></li>
      </ul>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-10">
    <canvas id="canvas"></canvas>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var doughnutData = [
      <% if !@distribution["Small"].nil? %>
        {
          value: <%= @distribution["Small"] %>,
          color:"#F7464A",
          highlight: "#FF5A5E",
          label: "Small"
        }
        <% if !@distribution["Medium"].nil? or !@distribution["Large"].nil? or !@distribution["XL"].nil? or !@distribution["XXL"].nil? or !@distribution["XXXL"].nil?  %>
          ,
        <% end %>
      <% end %>
      <% if !@distribution["Medium"].nil? %>
        {
          value: <%= @distribution["Medium"] %>,
          color: "#46BFBD",
          highlight: "#5AD3D1",
          label: "Medium"
        }
        <% if !@distribution["Large"].nil? or !@distribution["XL"].nil? or !@distribution["XXL"].nil? or !@distribution["XXXL"].nil?  %>
          ,
        <% end %>
      <% end %>
      <% if !@distribution["Large"].nil? %>
        {
          value: <%= @distribution["Large"] %>,
          color: "#FDB45C",
          highlight: "#FFC870",
          label: "Large"
        }
        <% if !@distribution["XL"].nil? or !@distribution["XXL"].nil? or !@distribution["XXXL"].nil?  %>
          ,
        <% end %>
      <% end %>
      <% if !@distribution["XL"].nil? %>
        {
          value: <%= @distribution["XL"] %>,
          color: "#949FB1",
          highlight: "#A8B3C5",
          label: "XL"
        }
        <% if !@distribution["XXL"].nil? or !@distribution["XXXL"].nil?  %>
          ,
        <% end %>
      <% end %>
      <% if !@distribution["XXL"].nil? %>
        {
          value: <%= @distribution["XXL"] %>,
          color: "#4D5360",
          highlight: "#616774",
          label: "XXL"
        }
        <% if !@distribution["XXXL"].nil?  %>
          ,
        <% end %>
      <% end %>
      <% if !@distribution["XXXL"].nil? %>
        {
          value: <%= @distribution["XXXL"] %>,
          color: "#8D5360",
          highlight: "#616774",
          label: "XXXL"
        }
      <% end %>
      ];
      var ctx = document.getElementById("canvas").getContext("2d");
      window.myDoughnut = new Chart(ctx).Doughnut(doughnutData, {responsive : true});
  });
</script>

app/views/reports/user_completion.html.erb
<div class="row">
  <div class="col-md-3">
    <fieldset>
      <legend>Legend</legend>
      <ul style="padding-left: 0px; list-style-type: none">
        <li>
          <span style="background-color: #F7464A; border: 1px solid #FF5A5E">&nbsp;&nbsp;&nbsp;&nbsp;</span> Have registered<span class="text-right pull-right"><%= @users %></span>
        </li>
        <li>
          <span style="background-color: #46BFBD; border: 1px solid #5AD3D1">&nbsp;&nbsp;&nbsp;&nbsp;</span> Have information<span class="text-right pull-right"><%= @infos %></span>
        </li>
        <li>
          <span style="background-color: #FDB45C; border: 1px solid #FFC870">&nbsp;&nbsp;&nbsp;&nbsp;</span> Have applied<span class="text-right pull-right"><%= @apps %></span>
        </li>
      </ul>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-9">
    <canvas id="canvas"></canvas>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var barChartData = {
      labels : ["Registered","Information","Applied"],
      datasets : [
        {
          fillColor : "#F7464A",
          data : <%= [@users, @infos, @apps] %>
        }
      ]
    }
    var ctx = document.getElementById("canvas").getContext("2d");
    window.myBar = new Chart(ctx).Bar(barChartData, {
      responsive : true
    });
    myBar.datasets[0].bars[1].fillColor = "#46BFBD";
    myBar.datasets[0].bars[1].highlightFill = "#5AD3D1";
    myBar.datasets[0].bars[2].fillColor = "#FDB45C";
    myBar.datasets[0].bars[2].highlightFill = "#FFC870";
  });
</script>

app/views/reports/user_last_sign_in_at.html.erb
<div class="row">
  <div class="col-md-3">
    <fieldset>
      <legend>Last login</legend>
      Total Users:
      <span class="text-right pull-right">
        <%= @number_of_users %>
      </span>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-9">
    <canvas id="canvas"></canvas>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var barData = {
      labels: [<%= "'#{@labels.join("', '")}'".html_safe %>],
      datasets: [{
        label: "Last login",
        fillColor: "rgba(151,187,205,0.5)",
        strokeColor: "rgba(151,187,205,0.8)",
        highlightFill: "rgba(151,187,205,0.75)",
        highlightStroke: "rgba(151,187,205,1)",
        data: [<%= @datapoints.join(', ') %>]
      }]
    };
    var ctx = document.getElementById("canvas").getContext("2d");
    window.myLine = new Chart(ctx).Bar(barData, {responsive : true});
  });
</script>

app/views/reports/user_last_sign_in_at_report.html.erb
<% @colors = ['#F7464A', '#46BFBD', '#FFC870', '#949FB1'] %>
<div class="row">
  <div class="col-md-3">
    <fieldset>
      <legend>Last login</legend>
      <ul style="padding-left: 0px; list-style-type: none">
        <% count = 0 %>
        <% @counts.each do |key, value| %>
          <li>
            <span style="background-color: <%= @colors[count] %>; width: 10px; border: 1px solid <%= @colors[count] %>">
              &nbsp;&nbsp;&nbsp;
            </span>
            &nbsp;
            <%= key %>
            <span class="text-right pull-right">
              <%= value %>
            </span>
          </li>
          <% count+= 1 %>
        <% end %>
      </ul>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-9">
    <canvas id="canvas"></canvas>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var doughnutData = [
      <% count = 0 %>
      <% @counts.each do |key, value| %>
        {
          value: <%= value %>,
          color: "<%= @colors[count] %>",
          highlight: "<%= @colors[count] %>",
          label: "<%= key %>"
        }
        <% count+= 1 %>
      <% if count < @counts.count %>
        ,
      <% end %>
      <% end %>
      ];
      var ctx = document.getElementById("canvas").getContext("2d");
      window.myDoughnut = new Chart(ctx).Pie(doughnutData, {responsive : true});
  });
</script>

app/views/reports/user_sign_up_distribution.html.erb
<div class="row">
  <div class="col-md-3">
    <fieldset>
      <legend>Sign Up Distribution</legend>
      Total Users:
      <span class="text-right pull-right">
        <%= @months.count %>
      </span>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-9">
    <canvas id="canvas"></canvas>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var barData = {
      labels: [<%= "'#{@month_names.join("', '")}'".html_safe %>],
      datasets: [{
        label: "Sign Up",
        fillColor: "rgba(50,177,80,0.2)",
        strokeColor: "rgba(122,220,122,0.8)",
        highlightFill: "rgba(50,177,80,0.5)",
        highlightStroke: "rgba(122,220,122,1)",
        data: [<%= @month_counts.values.join(', ') %>]
      }]
    };
    var ctx = document.getElementById("canvas").getContext("2d");
    window.myLine = new Chart(ctx).Bar(barData, {responsive : true});
  });
</script>

app/views/reports/user_sign_up_distribution_report.html.erb
<div class="row">
  <div class="col-md-3">
    <fieldset>
      <legend>Sign Up Distribution</legend>
        Total Users:
        <span class="text-right pull-right">
          <%= @months.count %>
        </span>
      <hr/>
    </fieldset>
  </div>
  <div class="col-md-9">
    <canvas id="canvas"></canvas>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var lineData = {
    labels: [<%= "'#{@month_names.join("', '")}'".html_safe %>],
    datasets: [
      {
          label: "Sign Up",
          fillColor: "rgba(50,177,80,0.2)",
          strokeColor: "rgba(122,220,122,1)",
          pointColor: "rgba(220,122,220,1)",
          pointStrokeColor: "#fff",
          pointHighlightFill: "#fff",
          pointHighlightStroke: "rgba(220,220,220,1)",
          // <%= @month_counts.keys.join(', ') %>
          data: [<%= @month_counts.values.join(', ') %>]
      }
    ]
  };
      var ctx = document.getElementById("canvas").getContext("2d");
      window.myLine = new Chart(ctx).Line(lineData, {responsive : true});
  });
</script>

app/views/reports/volunteer_application_comments.html.erb
<h1>Volunteer Application Comments</h1>

<% if @rows.nil? or @rows.length == 0 %>

  <h3>No data to display. <i class="fa fa-frown-o">&nbsp;</i></h3>

<% else %>
<%= link_to "Export all", reports_volunteer_application_comments_export_path, class: "btn btn-default" %>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
            <th class="hidden">Volunteer Application ID</th>
            <th>Name</th>
            <th>Choices</th>
            <th>Coordinator notes</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @rows) do |row| %>
            <td class="hidden"><%= row.id %></td>
            <td><%= [row.first_name, row.last_name].join(' ') %></td>
            <td><%= [row.choice1, row.choice2, row.choice3].join(', ') %></td>
            <td><%= row.coordinator_notes %></td>
            <td><%= link_to content_tag(:span, content_tag(:i, '&nbsp;'.html_safe, :class => "fa fa-external-link") + 'Review Application'), review_user_applications_path(row.id) %></td>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @rows %>
<% end %>

<script type="text/javascript">$('h1').parent().removeClass('container').addClass('container-fluid')</script>