config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :volunteer_position_contacts
  resources :user_informations, :concerns => :paginatable

  resources :user_applications, :concerns => :paginatable do
    collection do
      get 'success', action: :success
      get ':id/review', action: :review, as: :review
      get ':id/view', action: :view, as: :view
      post 'accept_or_deny', action: :accept_or_deny
      post 'reset/:id', action: :reset
    end
  end

  resources :volunteer_positions

  devise_for :users, controllers: {sessions: 'sessions'}

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Upmin::Engine => '/admin'
  end

  root 'pages#home'
  get '/about' => 'pages#about'
  get '/permissions' => 'pages#permissions'
  get '/codeofconduct' => 'pages#code_of_conduct'
  get '/user_information/fake' => 'pages#fake_user_info'
  get '/privacypolicy' => 'pages#privacy'
  get '/help' => 'pages#help'

  # Two factor authentication routes
  get '/two_factor_authentication' => 'users#two_factor_authentication'
  get '/two_factor_authentication/configure' => 'users#setup_2fa'
  post '/two_factor_authentication/enable' => 'users#enable_2fa'
  post '/two_factor_authentication/disable' => 'users#disable_2fa'
  get '/two_factor_authentication/disable' => 'users#prepare_disable_2fa'

  # Reports routes
  get '/reports' => 'reports#index'
  get '/reports/export_user_applications'
  post '/reports/export_user_applications'
  get '/reports/position_popularity' => 'reports#position_picks'
  get '/reports/user_distribution' => 'reports#user_completion'
  get '/reports/t_shirt_distribution'
  get '/reports/user_sign_up_distribution'
  get '/reports/user_last_sign_in_at'
  get '/reports/volunteer_application_comments', concerns: :paginatable
  get '/reports/volunteer_application_comments_export'

end

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Jazzify</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Volunteer<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Volunteer Positions", volunteer_positions_path %></li>
            <% if user_signed_in? %>
              <% if current_user.user_application.nil?  %>
                <% unless current_user.user_information.nil? %>
                  <li><%= link_to "My Information", user_information_path(current_user.user_information.id) %></li>
                <% end %>
                <li><%= link_to "Apply", new_user_application_path %></li>
              <% else %>
                <li><%= link_to "My Application", view_user_applications_path(current_user.user_application.id) %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <% if user_signed_in? and current_user.is_elevated? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.role.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if current_user.is_admin? %>
              <li><%= link_to "Admin Panel", upmin_url %></li>
              <li class="divider"></li>
              <li><%= link_to 'Create Volunteer Position', new_volunteer_position_path %></li>
              <li><%= link_to 'Volunteer Position Contact', volunteer_position_contacts_path %></li>
            <li class="divider"></li>
            <% end %>
            <li><%= link_to "User Informations", user_informations_path %></li>
            <li><%= link_to "User Applications", user_applications_path %></li>
            <div class="divider"></div>
            <li><%= link_to "Reports", reports_path %></li>
            <li><%= link_to "Permissions", permissions_path  %></li>
          </ul>
        </li>
        <% end %>
        <li class=""><a href="/about">About <span class="sr-only"></span></a></li>
        <li><%= link_to 'Help', help_path %></li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Account<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Change Password', edit_user_registration_path %></li>
            <li><%= link_to "Two Factor Authentication", two_factor_authentication_path %></li>
            <!-- <li class="divider"></li> -->
            <!-- <li><a href="profile/bill">My Bill</a></li> -->
          </ul>
        </li>
      </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Sign in", new_user_session_path, :class => 'navbar-link'  %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag '/favicon.ico' %>
  <title>
    Jazzify
    <% if @title %>
       | <%= @title %>
    <% end %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <% if @home %>
    <div class="">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "home-flash alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%== msg %>
        <% end %>
      <% end %>
  <% else %>
    <div class="container padding-top-for-fixed-navbar">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%== msg %>
      <% end %>
    <% end %>
  <% end %>
  <%= yield %>
  </div>
</body>
</html>